name: Lint helm chart

on:
  push:
    branches:
      - master
    paths:
          - 'helm/sloop/**'
  pull_request:
    branches:
      - "*"
    paths:
          - 'helm/sloop/**'

jobs:
  lint-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup helm
        uses: azure/setup-helm@v4

      - name: Lint chart
        run: |
          helm lint helm/sloop
